### ISSUE TITLE
Case Information

### ISSUE THREAD

**Issue by leifniem** [LouWii/ErgoMax#2]
A friend of mine wants my help building this board and i'm a little lost on the case part of the keyboard.

The included STEP / STL file would be suitable for 3D printing if i'm not mistaken, but it seems to be lacking the cutouts for the connectors, if i assume correctly.

On the acrlyic version i fail to understand if multiple middle layers are needed to acommodate the distance between switches and PCB, or alternatively a thicker middle part.

Sorry to bug if those are things that should be self-explanatory.

Thanks :)

**Comment by LouWii** [comment]
Hi,

I'll be completely honest, I'm a complete noob in regards to 3d modelling. And I don't remember entirely what I produced for this board. The step/stl is probably un-complete, since I didn't go for 3d printing. I used it more as a preview to see how it would look.

The acrylic version should work though, since that's the route I went for. But again, I don't remember entirely what I did there 🤦‍♂️ The workshop I went to didn't have a large choice of thicknesses, so I had to accommodate for that in my design.

**Comment by leifniem** [comment]
No worries, my friend just ordered all the parts so it's not remotely too late :)

But good to know my assumption about the 3D thing was right. With the vector files of the acrylic I should be able to whip up a printable case I think, I'll let you know in case we try that.

Thanks a lot and I hope you had a great vacation :)

**Comment by LouWii** [comment]
Good luck! I'd love to see a few pics once it's all built

**Comment by leifniem** [comment]
> Do you know how thick the acrylic needs to be to cut it?

We went for a 3D printed case, so I sadly do not

**Comment by jaspreetlall** [comment]
@leifniem Any chance you could share the 3D printable case files? Would really appreciate if you could.

Thank you.

**Comment by leifniem** [comment]
> @leifniem Any chance you could share the 3D printable case files? Would really appreciate if you could.
> 
> Thank you.

Never got around to fixing them. How fit are you with CAD?

**Comment by jaspreetlall** [comment]
No worries. I thought of asking since you mentioned choosing to go with printing. Thank you for your reply though.

And I barely ever used CAD but have someone I know who can tinker a little bit. They'd be able to tweak things but not design per se. What kind of fixes might be needed? I can definitely ask them.

**Comment by leifniem** [comment]
> No worries. I thought of asking since you mentioned choosing to go with printing. Thank you for your reply though.
> 
> And I barely ever used CAD but have someone I know who can tinker a little bit. They'd be able to tweak things but not design per se. What kind of fixes might be needed? I can definitely ask them.

My friend who had to file the case to measure is currently on vacation, so I cannot give you the exact modifications he had to make, but  think it was standoffs and cutouts for the USB ports and bridge cable. I'll see if I can find pictures of it.

**Comment by jaspreetlall** [comment]
Thank you, pictures would be helpful to plan in the mean time.
It's okay too if you aren't able to find those, can wait for your friend to be back from vacation 🙂.
Thank you once again.
